"""
Django settings for pdf_crawler project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import dj_database_url


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+f88-+hy4ru#bj=oqnu1bu^)mr#0&uo!##2t722r=os^-6v@!y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES = {
    'default': {
    }
}

DATABASES['default'].update(db_from_env)
