"""
Django settings for pdf_crawler project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

if os.environ.get('SITE_CONFIG') == 'LOCAL':
    from settings_dev import *
else:
    from settings_prod import *
